### PR TITLE
Game

### PR DESCRIPTION
**Pull request by somin-power**

### CODE REVIEW

**Comment by MedovTimur** [comment]
It's necessary to fix test

**Comment by somin-power** [comment]
> It's necessary to fix test

I am unable to fix my test code. When executing system.spend_blocks(200);, I always get the error: "internal error: entered unreachable code: GasTree corrupted! NodeNotFound."

**Comment by MedovTimur** [comment]
then test the logic without checking the delayed message

**Comment by Qpwan252** [comment]
> then test the logic without checking the delayed message



> then test the logic without checking the delayed message

I have already checked the logic correctness and the game states at each stage as per your request, and they have passed the checks. Is there any additional verification needed?

**Comment by MedovTimur** [comment]
All is well :)

**Pull request merged**
